### ISSUE TITLE
Version 2.0 - Scope & Features

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx-health-plan#123]
# 2.0 Release Overview

_Complementary to [Roadmap](https://github.com/lightspeeddevelopment/lsx-health-plan/blob/master/roadmap.md)._

### New Features

- [x] WooCommerce Memberships Integration
- [x] New Plans templates
- [x] New Workouts templates 
- [x] New Exercises templates 
- [x] New Meals templates
- [x] New Recipe templates
- [x] Various Shortcodes
- [x] WooCommerce Integration
- [x] Multi-plan Functionality
- [x] Integrate related blog posts on all Single HP pages
- [x] Integrate LSX Team on all Single HP pages
- [x] Integrate LSX Search on all archive templates
- [x] Integrate LSX Sharing on Single Plans
- [x] Add support for the LSX Customizer colour options #124
- [x] Enable Hierarchical post types for plans, workouts & meals
- [x] Update Plans, Meals, Workouts menus in WP-Admin

### Settings

- [x] Migrate settings to use CMB2 
- [x] Move the settings under Plans menu in WP-Admin
- [x] Remove the LSX Search settings
- [x] Move the search & filtering options to the LSX Search extension settings page

### My Plans 

- [x] My Plans Dashboard #137
- [x] My Plans Account Details 
- [x] Add a section to "My Plans Account Details" for "My Stats" with a BMI Calculator 
- [x] Add a progress bar to the active plan and grey out inactive plans
- [x] My Plan Weeks order not working #131
- [x] My Plan - Title / URL Enhancements #90
- [x] My Plan Weeks order not working #131

### Plans

- [x] Plans Landing page [#140, #141]
- [x] Single Plan [#139, #138]
- [x] Plan main tab #144
- [x] Workout tab #146
- [x] Meal tab #147
- [x] Warmup tab #145
- [x] Add "Plan Type" custom taxonomy.
- [x] Add support for LSX Sharing icons to display on a single plan

### Meals

- [x] Meals landing page archive template
- [x] Integrate tips post type into meals
- [x] Single Meal template with & without tips displaying
- [x] Add support for LSX Search options and filtering to the Meals post type and taxonomy archives

### Recipes

- [x] Integrate tips post type into recipes
- [x] Add support for LSX Search options and filtering to the Recipes post type and taxonomy archives
- [x] Add Cuisines taxonomy & frontend templates

### Workouts

- [x] Integrate tips post type into workouts
- [x] Add support for LSX Search options and filtering to the Workouts post type and taxonomy archives
- [x] Add Workout Type Category
- [x] Enhance styling for workout singles #106
- [x] Workout Single page #119
- [x] Loading workouts does not save all fields from the exercise groups #118
- [x] Workouts landing page #121

### Exercises

- [x] Integrate tips post type into exercises
- [x] Exercise Landing Page #86
- [x] Exercise Taxonomy Landing (muscle group, equipment etc) #87
- [x] Exercise - Single / Modal #88
- [x] Add options to show full content, excerpt or no content for exercise modals #130
- [x] Exercise Single page #114 
- [x] Workout Tab - Exercise layout options #112
- [x] Items shortcode needs to be available when exercise is not active too #107
- [x] Exercise - Translations #89
- [x] Add Items Shortcode #92

### WooCommerce Integration

- [x] WC Membership - Restricted Content not restricted from REST + WP Query #111
- [x] Single Plan Add to Cart Button
- [x] WooCommerce Health Plan Product Type
- [x] WooCommerce Plugin Integration #154
- [x] Single Plan "Add to Cart" or "Signup Now" Button
