### ISSUE TITLE
Refactor the Classes folder with subfolders

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/lsx-health-plan#46]
**Problem**
The classes folder is becoming too large, there are lots of files in the root.

**Solution**
We are going to add in 2 subfolders and move the classes into those.  

**IMPORTANT**
You will need to use the terminal command `git mv <source> <destination>` to move the files,  that way the git history is retained.

**Example**
1. You will `cd` into the `lsx-health-plan/classes` directory. 
2. Then create the new directory `integrations`.
3. Then run `git mv class-woocommerce.php integrations/woocommerce.php`

**Tasks**
- [x] create the integrations folder
- [x] `integrations/class-woocommerce.php`
- [x] `integrations/class-lsx-search.php`
- [x] `integrations/class-wp-user-avatar.php`
- [x] `integrations/class-downloads-monitor.php (this will rename the `class-downloads.php` file to `class-downloads-monitor.php`)
- [x] Fix the initiation of the downloads monitor class and class name.
- [x] create the `classes/post-types` folder
- [x] `post-types/class-plan.php`
- [x] `post-types/class-meal.php`
- [x] `post-types/class-tip.php`
- [x] `post-types/class-receipe.php`
- [x] `post-types/class-video.php`
- [x] `post-types/class-workout.php`
- [x] Fix the path to the classes in `class-post-types.php`
