### ISSUE TITLE
Exercises - Add a drop down meta field for "Right Side" and "Left Side"

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/lsx-health-plan#99]
### Is your enhancement related to a problem? Please describe.
We need to be able to show that certain exercises are for specific sides of the body. 

### TODO
- [x] Edit Exercise: Add a drop down field for "Right Side" and "Left Side", this field can be left blank.
- [x] Add in an `lsx_hp_exercise_title()`  function which outputs the title and the side.
- [x] The return html and the argument must be 'filtered' to allow 3rd party access.

### Designs
If entered, the "side" will display after the exercise title, on all pages. the function mentioned above will need to be replaced on all of the exercise templates.
